os:
- linux
language: python
python:
- 3.6
- 3.7
- 3.8
install: pip install -U tox-travis tox-pip-version codecov
script:
- tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: "__token__"
  skip_existing: true
  password:
    secure: UZtcsg82hiY0zRECCN2S2oB7w8K4qhMnYmwlt0mxBzggxYZiHNL+WDEyao1ahmURVoMHe9rcv9V0iD94tdTHVlbwVDMEZWExA02YJgk/xsRQOifUt2rJXj6C+piOEFSes9htYdspM7AmohoapIlyqDvtRjEMjXbpNxCDItqMyGoxh7+PFJgmQbyHsid11SfHGMMI2L8lbw6UZo1Zhz8WAcwW9U1tR1jQdydcBFQJ7XjH8IafrIL+QL4WyLIV/IX9gYXdh92MRiMvIln5O1Pvx5XcNVHwe0s3yK9e21XStNJUfCgtaD3ak1/q7p5n6Wxv6nN6HZkwUlqXzIs9k+yDufIsnlwu/GMwCZUN76nkm0pVe7Ozojj3YaNa+/pFrfEZmTGVVhwN66XzxtLA2OlTeQGFqYntlbv/DQMPfsOCm0iIdkWrNCemj09r/jxhhZZuzF6F/nsAl4FyMH6NeaiCLcZtgQiym8myv7uyxsPS65Lf0e+JDa7HcSrGsK7ucHCX0y5mkBq0ID9pr37Nhs31BaQ1PzUm+/J3r5Jj/pTNMMMDiUAUoEsBPoIZ39mjoME0xD3x7gi8dFS4wIO6m/TqtGU9+jKSDi1lv19lrDVc4Na/sEaqaaZOw+gq+DT9HzbT+TGNFN5MiVhX8VkE0KRdJav9fAhEEjAnKNqef4bQBUg=
  on:
    tags: true
    repo: adriangb/scikeras
after_success:
- codecov
